#!/bin/sh


gnome-terminal --tab-with-profile=Unnamed --title="server1" -- python3 mpworker.py 8000
gnome-terminal --tab-with-profile=Unnamed --title="server2" -- python3 mpworker.py 8001
gnome-terminal --tab-with-profile=Unnamed --title="server3" -- python3 mpworker.py 8002
gnome-terminal --tab-with-profile=Unnamed --title="server4" -- python3 mpworker.py 8003
